# Generated by Django 2.1.7 on 2019-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_car', models.CharField(max_length=200)),
                ('type_of_car', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=6)),
                ('alt_city', models.CharField(max_length=100)),
                ('alt_state', models.CharField(max_length=2)),
                ('alt_address', models.CharField(max_length=100)),
                ('alt_zip_code', models.CharField(max_length=6)),
            ],
        ),
    ]
